kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: route
  namespace: application-1
  labels:
    app: webserver
spec:
  to:
    kind: Service
    name: webserver
  port:
    targetPort: 8080-tcp
