apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-apps
spec:
  background: true
  mutateExistingOnPolicyUpdate: true
  rules:
    - match:
        any:
          - resources:
              kinds:
                - Pod
              selector:
                matchLabels:
                  critical: "true"
      mutate:
        patchStrategicMerge:
          spec:
            nodeSelector:
              matchLabels:
                node-role.kubernetes.io/workerpool-canary: ""
        targets:
          - apiVersion: apps/v1
            kind: Pod
            name: '{{ request.object.metadata.name }}'
            namespace: '{{ request.object.metadata.namespace }}'
      name: mutate-apps
  validationFailureAction: Audit

